### ISSUE TITLE
Replicating the results in papers -- Evaluation Details?

### ISSUE THREAD

**Issue by harryzhangOG** [columbia-ai-robotics/umpnet#1]
Dear authors, thanks for releasing the code and congrats on the RA-L acceptance! We are trying to replicate the results listed in Table II (goal-conditioned manipulation) because we want to test our model using the exact same pipeline you used. May I ask the details of evaluations you ran? For example, we are running the `test_quantitative.py` as-is with the default parameters (100 trials for each category). Does this suffice to replicate the results reported? 

Another thing is, how were the test pickle files in test_data generated? How are the sampled object pose and joint states distributed? 

Thanks.

**Comment by zhenjia-xu** [comment]
The previous `test_quantitative .py` has a small bug, which has been fixed in the latest version. The default parameters are sufficient to replicate the results reported in the paper.

If `scene_state =None`, the `reset()` function in `sim.py` will randomly sample a scene. The scene state (e.g., object pose, joint state) is then achieved by `get_scene_state()` and stored in a pickle file.

**Comment by harryzhangOG** [comment]
Hi, thanks for the update. 

We are loading the `test_data` pickle files as `scene_state` and we are curious how did you generate the randomized viewpoints and where are the camera parameters recorded/created? 
We noticed that in here https://github.com/columbia-ai-robotics/umpnet/blob/main/sim.py#L304
you are randomizing the base pose of the object. Is this the same as how the test_data was generated?
Thanks.

**Comment by zhenjia-xu** [comment]
Object position is fixed (center of the workspace), but the orientation about the z-axis will be randomly sampled.
The camera pose is fixed. Other camera parameters can be found [here](https://github.com/columbia-ai-robotics/umpnet/blob/main/sim.py#L48).
Our test data is generated by the `reset()` function exactly.

**Comment by harryzhangOG** [comment]
Thanks. Closing this for now.
