### ISSUE TITLE
partnet with other simulators

### ISSUE THREAD

**Issue by shivanimall** [columbia-ai-robotics/umpnet#3]
Wondering in UMPNet while using PartNet, did you find it more effective than directly using it in SAPIEN over bullet? Also, did you also try using PartNet in robosuite / mujoco?

Thanks for making this available, it is great work!

**Comment by zhenjia-xu** [comment]
The reason to use PyBulelt is that we have lots of existing code on it and this simulator is enough for articulated object manipulation. I'm not sure whether SAPIEN is more effective or not. As to the other two, I'm not familiar with robosuite; but it will be a bit complex to load URDF into mujoco.

**Comment by shivanimall** [comment]
Many thanks for the help @zhenjia-xu
